-- glucose-log v0.1용 참고 SQL
-- 이미 Supabase에서 glucose_records 테이블과 정책을 만들었다면 다시 실행할 필요 없습니다.

create table if not exists public.glucose_records (
  id bigint generated by default as identity primary key,
  record_date date not null unique,
  morning_glucose integer,
  evening_glucose integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.glucose_records enable row level security;

-- 아래 정책은 '로그인된 사용자'가 기록을 읽고/추가/수정/삭제할 수 있게 합니다.
-- 아빠 계정만 만들어 둔 현재 구조에 맞는 v0.1 정책입니다.

create policy "Dad can read glucose records"
on public.glucose_records
for select
to authenticated
using (true);

create policy "Dad can insert glucose records"
on public.glucose_records
for insert
to authenticated
with check (true);

create policy "Dad can update glucose records"
on public.glucose_records
for update
to authenticated
using (true)
with check (true);

create policy "Dad can delete glucose records"
on public.glucose_records
for delete
to authenticated
using (true);
